export interface RefundItem {
  refundItemId?: number;
  refundRequestId?: number;
  wineOrderItemId: number;
  quantity: number;
  reason: string;
}

export interface RefundRequest {
  refundRequestId?: number; // This can also be optional since it will be generated by the backend for new requests
  wineOrderId: number;
  requestDate?: Date; // This can be optional since the backend sets a default value
  status?: string; // This can be optional since the backend might set a default value
  refundItems: RefundItem[];
}

